In [7]:
library(tidyverse)

In [8]:
cv_results <- read_csv(
    "ml_algorithms/results/svm_paper_cv.csv"
)

New names:
• `` -> `...1`
Rows: 7 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1
dbl (4): Cef, Cip, Mer, Tob

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [9]:
cv_results

  ...1            Cef       Cip       Mer       Tob
1 genexp          0.7910599 0.8119587 0.8746823 0.8838510
2 genexp+snps     0.7395416 0.8266246 0.8684215 0.8897964
3 gpa             0.6799746 0.7811176 0.8683959 0.9071392
4 genexp+gpa      0.7696583 0.8179570 0.8703233 0.8903317
5 genexp+gpa+snps 0.7703086 0.8006709 0.8544422 0.8972458
6 gpa+snps        0.6529846 0.8949791 0.8726403 0.8932643
7 snps            0.6593780 0.8825963 0.5803940 0.8857142

## Analyze data on different data type combinations from the paper

In [4]:
performances <- read_csv(
    "./other_data/perf_all.csv"
)

Rows: 280 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): drug, cv_mode, mode
dbl (15): pos_recall, pos_recall_std, neg_recall, neg_recall_std, precision,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [36]:
head(performances)

  drug          pos_recall pos_recall_std neg_recall neg_recall_std precision
1 Meropenem     0.826      0.109          0.843      0.170          0.920
2 Tobramycin    0.647      0.390          0.852      0.175          0.667
3 Ciprofloxacin 0.679      0.266          0.859      0.123          0.857
4 Ceftazidim    0.782      0.210          0.815      0.240          0.806
5 Meropenem     0.759      0.140          0.820      0.210          0.902
6 Tobramycin    0.608      0.408          0.901      0.310          0.738
  precision_std npv   npv_std balanced_accuracy balanced_accuracy_std
1 0.081         0.688 0.118   0.834             0.100
2 0.361         0.841 0.210   0.750             0.129
3 0.213         0.683 0.155   0.769             0.156
4 0.129         0.791 0.233   0.798             0.126
5 0.102         0.608 0.173   0.790             0.129
6 0.413         0.834 0.318   0.755             0.181
  F1-score_micro F1-score_micro_std F1-score_macro F1-score_macro_std AUC
1 0.870          0.085              0.814          0.090              0.877
2 0.657          0.306              0.752          0.112              0.823
3 0.758          0.229              0.760          0.164              0.798
4 0.794          0.147              0.798          0.129              0.862
5 0.825          0.099              0.762          0.120              0.883
6 0.667          0.358              0.767          0.209              0.803
  cv_mode  mode
1 block_cv expr
2 block_cv expr
3 block_cv expr
4 block_cv expr
5 block_cv expr_snps
6 block_cv expr_snps

In [5]:
performances_filtered <- performances %>%
    filter(cv_mode == "standard_cv") %>%
    filter(drug == "Tobramycin") %>%
    select(c("drug", "F1-score_macro", "F1-score_macro_std", "mode") )
colnames(performances_filtered) <- c("drug", "F1_score_macro", "F1_score_macro_std", "mode")

In [6]:
performances_filtered %>%
    group_by(mode) %>%
    summarise(F1_score = mean(F1_score_macro))

  mode          F1_score
1 expr          0.8800
2 expr_snps     0.8830
3 gpa           0.9008
4 gpa_expr      0.9162
5 gpa_expr_snps 0.9010
6 gpa_snps      0.8926
7 snps          0.8806

# Logistic regression
## C = 1

Table of results: C = 1

Remember the definitions:
* precision s: ts / ts + fs
* recall s: ts / ts + fr
* precision r: tr / tr + fr
* recall r: tr / tr + fs

Comments: if C = 1, too many features are used (between 15000 and 22000 with coefficients higher than 0.01), so data risk to be overfitted. Better decrease C to have a stronger regularization. Same happens with 0.1, because l2 regularization is the Ridge regularization, which is useless in these cases (does not avoid overfit, it seems, but you should check using the performance on the training set if you want to write in the final paper).

The Lasso regression with the 'saga' solver seems to take too much time.

In [20]:
library(tidyverse)
log_reg_scores <- read_csv(
    "ml_algorithms/results/log_reg.csv"
)

New names:
• `` -> `...1`
Rows: 12 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): drug, features
dbl (5): ...1, precision_s, precision_r, recall_s, recall_r

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [21]:
log_reg_scores

   ...1 drug features precision_s precision_r recall_s  recall_r
1   0   Cef  genexp   0.7058824   0.6969697   0.7058824 0.6969697
2   1   Cef  gpa      0.6551724   0.6052632   0.5588235 0.6969697
3   2   Cef  snps     0.7000000   0.6486486   0.6176471 0.7272727
4   3   Cip  genexp   0.6756757   0.8000000   0.7812500 0.7000000
5   4   Cip  gpa      0.6111111   0.7222222   0.6875000 0.6500000
6   5   Cip  snps     0.6153846   0.7575758   0.7500000 0.6250000
7   6   Mer  genexp   0.7647059   0.8333333   0.5909091 0.9183673
8   7   Mer  gpa      0.5625000   0.7636364   0.4090909 0.8571429
9   8   Mer  snps     0.3125000   0.6909091   0.2272727 0.7755102
10  9   Tob  genexp   0.9000000   0.9090909   0.9642857 0.7692308
11 10   Tob  gpa      0.9016393   0.9523810   0.9821429 0.7692308
12 11   Tob  snps     0.9152542   0.9130435   0.9642857 0.8076923

In [22]:
log_reg_coefficients <- read_csv(
    "ml_algorithms/results/log_reg_coefficients.csv"
)

New names:
• `` -> `...1`
Rows: 4 Columns: 94268
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (94268): ...1, PA0263.1,tRNA-Arg, PA0296-PA0297,P1, PA0826.2,ssrA, PA083...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [23]:
log_reg_coefficients <- as_tibble(t(log_reg_coefficients))
colnames(log_reg_coefficients) <- c("Cef", "Cip", "Mer", "Tob")
log_reg_coefficients <- log_reg_coefficients %>%
    slice(-1)

In [25]:
log_reg_coefficients %>%
    select(Mer) %>%
    filter(abs(Mer) >= 0.01)

      Mer
1     -0.01059697
2      0.01021963
3      0.03006846
4      0.01125831
5      0.02784473
6     -0.02767340
7      0.01813623
8     -0.02749689
9     -0.02473497
10    -0.01111088
11     0.02156145
12    -0.01191889
13     0.01426810
14     0.02029269
15    -0.01065814
16    -0.01319657
17    -0.01980405
18     0.02167207
19    -0.01449325
20     0.01988415
21     0.02240769
22     0.01679117
23    -0.01720712
24    -0.01512308
25    -0.01874678
26    -0.02184970
27     0.01081131
28    -0.01338405
29     0.01271726
30     0.02177062
⋮     ⋮
12864  0.01217516
12865 -0.02602355
12866  0.01462160
12867 -0.01126002
12868 -0.02245212
12869  0.01366860
12870  0.02521139
12871  0.02963807
12872  0.02952241
12873  0.03043564
12874  0.02983883
12875  0.01327629
12876  0.02074117
12877  0.02913947
12878  0.01228540
12879  0.01617162
12880 -0.01412228
12881 -0.01416177
12882 -0.01303674
12883 -0.02006963
12884 -0.01393578
12885 -0.01387562
12886  0.01241952
12887 -0.01034800
12888 -0.02055059
12889 -0.01428691
12890 -0.01231660
12891 -0.01589804
12892 -0.01549003
12893 -0.01686120

## Logistic regression with dimensionality reduction